# VCP codes — from https://github.com/thlter/DDCCI_tool (MIT)

VCP_CODE = {
    'Restore Factory Color Defaults': 0x08,
    'Restore Factory Defaults': 0x04,
    'Restore Factory Geometry Defaults': 0x06,
    'Restore Factory Luminance / Contrast Defaults': 0x05,
    'Restore Factory TV Defaults': 0x0A,
    'Save / Restore Settings': 0xB0,
    'VCP Code Page': 0x00,
    'User Color Temperature Increment': 0x0B,
    'User Color Temperature': 0x0C,
    'Luminance': 0x10,
    'Clock': 0x0E,
    'Flesh Tone Enhancement': 0x11,
    'Contrast': 0x12,
    'Select Color Preset': 0x14,
    'Video Gain Red': 0x16,
    'Video Gain Green': 0x18,
    'Video Gain Blue': 0x1A,
    'Auto Setup': 0x1E,
    'Auto Color Setup': 0x1F,
    'Gray Scale Expansion': 0x2E,
    'Video Black Level: Red': 0x6C,
    'Video Black Level: Green': 0x6E,
    'Video Black Level: Blue': 0x70,
    'Gamma': 0x72,
    'Adjust Zoom': 0x7C,
    'Sharpness': 0x87,
    'Display Usage Time': 0xC0,
    'Display Controller ID': 0xC8,
    'Display Firmware Level': 0xC9,
    'OSD Language': 0xCC,
    'Power Mode': 0xD6,
    'VCP Version': 0xDF,
    'Input Source': 0x60,
    'Flat Panel Sub-Pixel Layout': 0xB2,
}

COLOR_PRESET_CODE = {
    'sRGB': 0x01,
    'Display Native': 0x02,
    '4000K': 0x03,
    '5000K': 0x04,
    '6500K': 0x05,
    '7500K': 0x06,
    '8200K': 0x07,
    '9300K': 0x08,
    '10000K': 0x09,
    '11500K': 0x0A,
    'User Mode 1': 0x0B,
    'User Mode 2': 0x0C,
    'User Mode 3': 0x0D,
}

AUTO_SETUP_CODE = {
    'off': 0x00,
    'Manual Perform': 0x01,
    'Continuous': 0x02,
}

POWER_MODE_CODE = {
    'on': 0x01,
    'off': 0x05,
}

OSD_LANG_CODE = {
    'Reserved/ignored': 0x00,
    'Chinese-traditional': 0x01,
    'English': 0x02,
    'French': 0x03,
    'German': 0x04,
    'Italian': 0x05,
    'Japanese': 0x06,
    'Korean': 0x07,
    'Portuguese-Portugal': 0x08,
    'Russian': 0x09,
    'Spanish': 0x0A,
    'Swedish': 0x0B,
    'Turkish': 0x0C,
    'Chinese-simplified': 0x0D,
    'Portuguese-Brazil': 0x0E,
    'Arabic': 0x0F,
    'Bulgarian': 0x10,
    'Croatian': 0x11,
    'Czech': 0x12,
    'Danish': 0x13,
    'Dutch': 0x14,
    'Estonian': 0x15,
    'Finnish': 0x16,
    'Greek': 0x17,
    'Hebrew': 0x18,
    'Hindi': 0x19,
    'Hungarian': 0x1A,
    'Latvian': 0x1B,
    'Lithuanian': 0x1C,
    'Norwegian': 0x1D,
    'Polish': 0x1E,
    'Romanian': 0x1F,
    'Serbian': 0x20,
    'Slovak': 0x21,
    'Slovenian': 0x22,
    'Thai': 0x23,
    'Ukrainian': 0x24,
    'Vietnamese': 0x25,
}

INPUT_SRC_CODE = {
    'Analog video (R/G/B) 1': 0x01,
    'Analog video (R/G/B) 2': 0x02,
    'Digital video (TMDS) 1 DVI 1': 0x03,
    'Digital video (TMDS) 2 DVI 2': 0x04,
    'Composite video 1': 0x05,
    'Composite video 2': 0x06,
    'S-video 1': 0x07,
    'S-video 2': 0x08,
    'Tuner 1': 0x09,
    'Tuner 2': 0x0A,
    'Tuner 3': 0x0B,
    'Component video (YPbPr / YCbCr) 1': 0x0C,
    'Component video (YPbPr / YCbCr) 2': 0x0D,
    'Component video (YPbPr / YCbCr) 3': 0x0E,
    'DisplayPort 1': 0x0F,
    'DisplayPort 2': 0x10,
    'Digital Video (TMDS) 3 HDMI 1': 0x11,
    'Digital Video (TMDS) 4 HDMI 2': 0x12,
}

FLAT_PANEL_SUB_PIXEL_LAYOUT_CODE = {
    0x00: 'Sub-pixel layout is not defined',
    0x01: 'Red / Green / Blue vertical stripe',
    0x02: 'Red / Green / Blue horizontal stripe',
    0x03: 'Blue / Green / Red vertical stripe',
    0x04: 'Blue/ Green / Red horizontal stripe',
    0x05: 'Quad-pixel, a 2 x 2 sub-pixel structure with red at top left, blue at bottom right and green at top right and bottom left',
    0x06: 'Quad-pixel, a 2 x 2 sub-pixel structure with red at bottom left, blue at top right and green at top left and bottom right',
    0x07: 'Delta (triad)',
    0x08: 'Mosaic with interleaved sub-pixels of different colors',
}
